services:
  db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - '${DB_PORT}:5432'
    volumes:
      - tele_pg_data:/var/lib/postgresql/data

volumes:
  tele_pg_data:
